### ISSUE TITLE
Calibration Issue

### ISSUE THREAD

**Issue by art804** [thomwolf/GreatSand#10]
I'm trying to run magic sand on a MS Surface Pro 4 running Windows 10 AU. Driver installs worked fine and everything is connected as it should be.

When the calibration runs, the solid white window that I assume is meant to fill the secondary (projector) display appears as a small rectangle within the main device screen (not full screen on the projector). The calibration process starts and I see the 'calibrating depth of field' or similar message flash up quickly, but this then disappears and kicks me out to the main screen. Here's what the early calibration screen looks like when I take a full screen snip (includes main display and projector display extended to the right):

![desktop](https://cloud.githubusercontent.com/assets/7828385/17546946/8f5dcff0-5f38-11e6-960c-ceb39b2ad23d.PNG)

I have the projection settings set to 'extend' the display to the projector. It seems like there is some issue with the program correctly detecting the position of the secondary (projector) screen?

Really keen to get this working - let me know if there's anything else I can provide.

**Comment by thomwolf** [comment]
Hi ashtonaut,
I was away from my computer for the past 2 weeks.
Did you managed to fix the problem ?
Are you sure your desktop is extended ? I can see a copy of the task bar on the second screen, is that normal ?
If you didn't get the soft to work I can send you a debug versionof the soft which is more verbose and should help us find the origin of the issue.

**Comment by art804** [comment]
Yes, desktop is extended (Windows 10 shows taskbar on secondary screen). I never got it to work so I gave up.

I suspect it might have something to do with the display scaling on the Surface, which is set to 200% by default. Perhaps this breaks the part of your code where (presumably) you calculate where the extended display screen should start to place the white calibration screen? Happy to test again if I can help debug this somehow. Thanks.

**Comment by thomwolf** [comment]
Here is a more verbose binary: [Magic Sand_win32_verbose.zip](https://github.com/thomwolf/Magic-Sand/files/438101/Magic.Sand_win32_verbose.zip)
You can try it and to see if it recognizes well the screen resolution and position of your screens (the projector should be screen 1).
But I am afraid you are right at pointing the 200% scaling of the Surface. It will be difficult to debug for me since I don't have a Surface :(

**Comment by art804** [comment]
Hi I gave this a go with results as follows:

log_200.txt is the log file with everything set up as normal. As noted in my OP, when I click calibrate a window pops up quickly then disappears. Screen looks as per the screenshot in my OP.

I then changed the display scaling to 100% and tried again. This is file log_100.txt.

Strangely, at 100% scaling the calibration process appeared to commence properly (chessboard patterns visible, but on primary display), whereas this didn't commence at 200% (I am stuck with a white box on the primary display).

However, even at 100% the 'secondary display' is visible exactly as per the screenshot in my OP.

Looking at the start of the log it seems like the software detects the screen sizes and positions correctly, but it just doesn't locate the calibration images on the secondary display like it should.

Any further thoughts? I'm happy to try testing again.

[log_100.txt](https://github.com/thomwolf/Magic-Sand/files/440476/log_100.txt)
[log_200.txt](https://github.com/thomwolf/Magic-Sand/files/440475/log_200.txt)

**Comment by thomwolf** [comment]
Ok thanks!
This is definitely a Window upscaling issue that is not yet solved in GLFW
(The underlying multi-plateform display framework).
I guess it is related to these issues
https://github.com/glfw/glfw/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20upscaling
https://github.com/glfw/glfw/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20upscaling
I will see if I can find a workaround. I will probably ask you to try a few
possibilities if you're ok.

**Comment by art804** [comment]
Happy to try anything you can suggest. I also tried changing the primary display resolution to make it lower resolution. It didn't matter which resolution I tried (1600x1200, 1024x768 etc), in every case the calibration white box appeared either entirely or partially on the primary screen, instead of entirely on the secondary screen (projector). Thanks.

**Comment by TimNe0** [comment]
Hi Ashtonaut

I have experienced exact same issues as detailed in your first post.  My laptop is a 4k screen which is badly supported by everyone.  I set my 2nd monitor (projector) to 800x600 but it was still dropping out.  I initially suspected a broken kinect but I think it was some problem with the calibration files getting corrupted.  My only difference was I sometimes got the calibration screen on a clean startup but then it'd go dark again after a few attempts at calibration.

My steps that appear to work were:

- ensure everything is setup properly and ready for calibration & turn on projector/kinect
- Turn on laptop, wait until logged in
- connect already on projector
- connect kinect
- run sdk install
- reinstall drivers
- unpack software into new directory
- run magic sand
- calibrate

I found that the application appears to self corrupt occasionally after 1+ calibration attempts (seems random).  Once my setup was calibrated I've zipped it all up and am just praying to the software gods that I can just unpack it when if/when it dies again.

**Comment by TimNe0** [comment]
Oh, and as I'm using a laptop with a high end nvidia graphics card, if you're in a similar situation make sure you right click on the app and chose to run with that graphics card.

**Comment by RasmusRPaulsen** [comment]
I had the same problem on a high-end Laptop using Windows 10.

I solved it using the method described here:
https://github.com/glfw/glfw/issues/676

Go into the visual studio project and  set
"Manifest Tool | Input and Output | DPI Awareness" to "Per Monitor High DPI Awareness"

**Comment by art804** [comment]
Is this issue fixed by the recent commit here?

https://github.com/thomwolf/Magic-Sand/commit/3e45c393efd94c569bd0193a8b653bf3976b36c6

**Comment by RasmusRPaulsen** [comment]
Hi,

The latest release that can be found here:
https://github.com/thomwolf/Magic-Sand/releases/tag/v1.5.4

Is compiled with "Per Monitor High DPI Awareness" and it works on my system.

It would be great, if you could test it and let us know how it goes.

There are major changes in how the calibration procedure now works. It is now more stepwise with more posibilities to locate errors in the process. This is explained in the release notes.

The application starts in a "setup mode" where the Kinect view can be seen and a white screen is shown on the projector - you should be able to use that as the first check.

Best,
Rasmus

**Comment by thomwolf** [comment]
@RasmusRPaulsen @ashtonaut so, does this work with High DPI in the latest release ?
If it is fixed we can close this thread, I guess.

**Comment by RasmusRPaulsen** [comment]
It works on my system - but I would like to hear from @ashtonaut if it works before closing the thread.

**Comment by art804** [comment]
OK, I have (finally) got around to testing the latest release with my Surface Pro. I can confirm that the previous calibration screen resolution issue appears to be solved, which is good news. I am having another issue now with the software crashing, but I'll open another issue for that. Thanks.
