### ISSUE TITLE
Calibration Issue

### ISSUE THREAD

**Issue by brodowaggins** [thomwolf/GreatSand#11]
When I complete the calibration I am left with this image projected on the sandbox:
![image](https://cloud.githubusercontent.com/assets/21272325/18024815/9a8bca16-6bc8-11e6-869c-c22f2dde4ecd.png)

I am using a Window's 10 PC with a decent graphic's card. 

Any help is greatly appreciated.

**Comment by thomwolf** [comment]
Hi,
It seems like 1-2 points of the calibration (on the bottom) were not
aquired. You should try to recalibrate. Check that the board you use to
cover the sandbox does not have reflective parts (like tape on it for
instance). The kinect sensor has a hard time acquiring depth on reflective
surfaces.

**Comment by Ritesh1991** [comment]
hi can we use room alive calibration .XML file with your code with multiple Kinects and projectors.so one can increase size of sandbox

**Comment by thomwolf** [comment]
Hi, not as is. The code only uses the first detected kinect.

**Comment by Ritesh1991** [comment]
can we improve it for room alive calibration file.i want to do work on it.need some guidance for it.

**Comment by thomwolf** [comment]
Sorry, I don't kown how room alive work.

**Comment by swoll001** [comment]
it will do the first 5 sand calibrations, but not the top of the box calibration. when that happens the screen doesnt show it. the projector does the grid but nothing happens. 
im on Mac Yosemite

**Comment by GED-dev-rr** [comment]
I have a problem with the magic sand not reading / seeing the kinect 

![Image](https://github.com/user-attachments/assets/83711108-b50c-4131-844c-28dc6824065e)
