### ISSUE TITLE
Calibration process issues?

### ISSUE THREAD

**Issue by DanielCake** [thomwolf/GreatSand#12]
Hey,

I've recently downloaded your .exe version of the project - but I'm having difficulty attempting to get the kinect to calibrate? I have installed all of the required 32-bit drivers using Zadig, but in the console for magic sand I keep getting this message - "setFromPixels(): allocating to match dimensions: 0 0" and also, "ofxKinect: update(): device 0 isn't delivering data, reconnecting tries: 1" - though if I use the display kinect depth view in the magic sand window, it does display the Kinect input. 

I'll continue to tinker, but any help with this would be fantastic! :-)

Thanks,

Daniel

**Comment by thomwolf** [comment]
Hi Daniel,
Could you try to run [this version of the soft](https://github.com/thomwolf/Magic-Sand/files/438101/Magic.Sand_win32_verbose.zip) which is more verbose and send me a copy of the log output ?
Also, which version of windows do you run and on which type of computer ?
Thanks,
Thom

**Comment by DanielCake** [comment]
Hey Thom,

I've just tried that version of the software - but I get an error about missing freeimage.dll?

I'm running on a desktop pc on Windows 10, 64-bit. :-)

Thanks,

Daniel

**Comment by thomwolf** [comment]
Well, the zip I sent you only contains the executable file. You have put it in the original folder of the previous installation which has all the required dll (you can rename it or erase the previous executable if needed)

**Comment by ibaranov-cp** [comment]
I have a similar issue, the .exe you provided crashes on launch, after about ~20 lines of debug output.

However, with the original executable, everything seems to get past calibration, then crashes. Attached are the calibration settings files.
[settings.zip](https://github.com/thomwolf/Magic-Sand/files/455732/settings.zip)

**Comment by thomwolf** [comment]
Hi,
Can you provide the debug output or does it closes too fast ?

**Comment by DanielCake** [comment]
Sorry for such a slow reply - I'm now running with the verbose exe and I have uploaded my console output to pastebin here: http://pastebin.com/xqbWX9v4

It opens the calibration settings, the projector output becomes white for about a second then, then disappears and if I attempt to interact with the software it then becomes unresponsive. 

Edit: 
If I click recalibrate after it's failed, in the verbose version - I get this. 
[verbose] KinectProjector: updateROIFromDepthImage(): ROI_CALIBRATION_STATE_READY_TO_MOVE_UP: got a stable depth image
[notice ] ofxCvFloatImage: setFromPixels(): allocating to match dimensions: 0 0

**Comment by DanielCake** [comment]
Hey - just wanted to let you know that it's working now - it's fantastic! 

Thanks so much for the help with the new exe :-)

Cheers,

Daniel

**Comment by thomwolf** [comment]
Great, what did you do to solve the issue ?
