### ISSUE TITLE
Calibration Mac

### ISSUE THREAD

**Issue by StraunB** [thomwolf/GreatSand#13]
I am having problems with my mac when it starts and tried to calibrate.  It seems to stop after the step when it detects the walls and then I just get a black screen.  Ive tried calibrating several times and it never goes past step two in the calibration.  Any ideas?  Ive built the setup almost exactly like yours.

**Comment by aszel** [comment]
I'm having the same problem. I can start the programme but it won't run through the whole calibrating process. I can see some pixels moving in the top left corner as soon as I add a fish or rabbit. What am I missing?

**Comment by StraunB** [comment]
I finally got mine to work.  Make sure you have it completely set up with sand and all.  Then use the advanced feature to make sure the kinect is pointed at the box properly and can see all 4 sides.  Even then, it takes several tries to get it to complete the calibration sometimes.  Also, make sure you have a perfectly flat cover for the second part of the calibration.  If its not flat, it wont calibrate properly.

**Comment by aszel** [comment]
Thanks for the info. Mine does work well, too. The problem was my projector. The image was not in the right angle. After playing with the adjustment it worked. It seems the programme just interupts the process as soon things go wrong without warning. Thank you for your support.

**Comment by thomwolf** [comment]
Thanks StraunB and aszel, I have updated the "calibration" section of the release page with these   advices.
