### ISSUE TITLE
Slow down the rampant rabbits

### ISSUE THREAD

**Issue by TimNe0** [thomwolf/GreatSand#16]
Excellent software (though the config seems a bit of black art as I've detailed in one of the issues below)

Is there a way of slowing down the rabbits and fish? Ours zoom across the screen so incredibly fast it's almost impossible to catch them.

**Comment by thomwolf** [comment]
Well currently it is only possible to change it in the source code.
I might come back to it to add this option but I have so much to do right that it probably won't be before a few months I am afraid.
