### ISSUE TITLE
vertex version error 

### ISSUE THREAD

**Issue by Ritesh1991** [thomwolf/GreatSand#17]
![glsl error](https://cloud.githubusercontent.com/assets/22499176/25312727/3d70d1b8-27d5-11e7-98cf-9750e421b5cf.png)
can you guide me what is problem here. because this error i cant get color on sand. 
system intel i3 with 2gb ram
navida gforce 210 graphics mfg by zotac
driver from navida website
win-7 32bit 

how i can solve this issue thanks

**Comment by thomwolf** [comment]
Hmm, I am worried your system might be too old for OpenGL required by the soft.
You can try to update the graphic card drivers though.

**Comment by Ritesh1991** [comment]
thanks for reply i solved error by adding one line in main.cpp  on line number 50 settings.setGLVersion(3, 3); but i need to update graphics card
