### ISSUE TITLE
color projection error 

### ISSUE THREAD

**Issue by Ritesh1991** [thomwolf/GreatSand#19]
here i attach snap shot of sandbox. i software run smoothly but it is not map kinect projection properly 
![color error on top left side](https://cloud.githubusercontent.com/assets/22499176/25704154/31484fae-308d-11e7-90f0-572f05aeb872.jpg)

**Comment by thomwolf** [comment]
Hi,
You should probably re-calibrate the sandbox (click on "advanced" and "calibrate")
