### ISSUE TITLE
1414 Kinect Sensor Not Widescreen?

### ISSUE THREAD

**Issue by trueproductions** [thomwolf/GreatSand#23]
Hello. I am building a sandbox for my office and it seems the Kinect Sensor can't see all 4 walls of my table. The table is 50" x 30".

Is there anything I can do in your software to tell it that my sandbox is not a perfect square?

**Comment by thomwolf** [comment]
Well the sandbox doesn't have to be a square but the walls of the sandbox should be in the field of view of the kinect. You can check that by clicking on "display kinect depth view".
