### ISSUE TITLE
Strange colored lines on Kinect RGB images during calibration

### ISSUE THREAD

**Issue by RasmusRPaulsen** [thomwolf/GreatSand#24]
I am trying to calibrate my Sandbox and get some truly strange results. Once it succeeded though. 
I have modified the source so it spits out some debug images. One is attached.
As can be seen there are colored lines going over the RGB images captured by the Kinect when doing the chessboard detection.
Anyone having similar issues? I suspect a faulty sensor or a driver problem?

![magicsanddrop_6-6-2017-13-13-0-0](https://cloud.githubusercontent.com/assets/14818460/26826975/620b65fc-4abb-11e7-93eb-8d4590768be9.png)

**Comment by thomwolf** [comment]
that looks like the colored wheels of the beamer recorded by the Kinect (you have the same if you film the sandbox with a good camera). My kinect 1414 doesn't catch taht. Which kind of kinect do you have ?

**Comment by RasmusRPaulsen** [comment]
Ah! That is very strange. I had no idea that projectors did that kind of hidden patterns.
My Kinect is the 1517 model. I only have a 1414 connected to my Xbox and I am hesitant to use that one.
The issue only comes 3 out of 4 times. I will see if I can find a solution.

**Comment by RasmusRPaulsen** [comment]
A colleague suggested that it is due to the short shutter time of the Kinect camera combined with (as you suggest) the way the beamer does color splitting.
Since it seems difficult/impossible to change the shutter time of the Kinect I believe that taking several frames and for example doing a temporal median filtering to create a stable image would be solution.
I might give it a go.

**Comment by thomwolf** [comment]
Yes, your colleague is right ! I guess you can try to average a few frame indeed. Openframework probably offers some simple way to do it.
