### ISSUE TITLE
Updated build info on Visual Studio 2015

### ISSUE THREAD

**Issue by RasmusRPaulsen** [thomwolf/GreatSand#25]
I have succesfully build the Magic Sand project on Windows 10 using Visual Studio 2015. Here is how I did it:

Magic sand build instructions (June 2017)

* Download version 0.9.8 of OpenFrameworks here: http://openframeworks.cc/
 - unpack into [source]\of_v0.9.8_vs_release
* Download ofxCv, ofxParagraph, ofxDatGui, ofxModal 
 - unpack them in the addons folder in the openframeworks folder: [source]\of_v0.9.8_vs_release\addons\
* Download latest GIT version of Magic Sand here: https://github.com/thomwolf/Magic-Sand
  - unpack  in the apps version of the openframeworks folder: [source]\of_v0.9.8_vs_release\apps\myApps
* Open the "Magic Sand.sln" solution file using VS2015
* Go into the project settings of the "Magic Sand" project (do this for both the debug and release version)
* In "Configuration Properties | C/C++ / Additional Include Directories" update include folders:
  some folders points to local folders on "Thoms system" - change them to relative directories "..\..\..\addons" 

[source] is your local source directory

@Thom : You might update the Magic Sand.sln solution to have relative include paths as described above.

**Comment by Parzivalcjxjxjdidjxjxixjdbdjcixdsuyys** [comment]
Hello, do you have the Magic Sand build for editing in Visual Studio 2022?
