### ISSUE TITLE
Crash in kinectCoordToWorldCoord

### ISSUE THREAD

**Issue by RasmusRPaulsen** [thomwolf/GreatSand#26]
I got a crash in kinectCoordToWorldCoord and found the following issue:

The y coordinate was larger than kinectRes.y this causes an out-of-bounds error in:
kc.z = FilteredDepthImage.getFloatPixelsRef().getData()[ind];

The call stack revealed that the bad y-coordinate originates in:
updateBeachDetection in vehicle.cpp where the future position becomes out of bounds.

A quick and dirty hack is to add:
	if (y < 0)
		y = 0;
	if (y >= kinectRes.y)
		y = kinectRes.y - 1;
	if (x < 0)
		x = 0;
	if (x >= kinectRes.x)
		x = kinectRes.x - 1;

to the start of
kinectCoordToWorldCoord

**Comment by thomwolf** [comment]
Thanks @RasmusRPaulsen , do you think you could do a PR with your path-cleaning and bug correction ?
I am not sure I will be able to start my old win-laptop and look into that before a few weeks at least.

**Comment by RasmusRPaulsen** [comment]
I will see what I can do but I am not an expert git user. Will keep you updated!
