### ISSUE TITLE
Can't see Kinect

### ISSUE THREAD

**Issue by tim-9red7** [thomwolf/GreatSand#27]
Running 10.9. Model 1414 connect sensor. 2013 MacBook air. Magic sand gets stuck on full calibration. It just says stabilizing acquisition. When I first open Magic send it says it still can't see the Connect yet I do see the device in device manager. Any ideas?

**Comment by thomwolf** [comment]
Can you see the view from the kinect when you click on "advanced" "display kinect depth view" ?
If yes then it is more a problem of calibration than kinect communication.

**Comment by thomwolf** [comment]
Please try with the new release and open back the issue if it still doesn't work.
Closing for now.
