### ISSUE TITLE
OK to leave Kinect on?

### ISSUE THREAD

**Issue by trueproductions** [thomwolf/GreatSand#30]
I have this setup in my office. The idea is to leave it running all day and night and use the projector's remote control to "turn it on"

This means the Kinect will be on and functioning all day and night. Is this OK?

**Comment by thomwolf** [comment]
I don't see any problem (but I have no in-depth knowledge of kinect, maybe
you should check on kinect forums)

**Comment by chboing** [comment]
Leave always ON ? I see a problem here, maybe you run on solar power batteries and still it's not ok to leave something always on from my point of view.
If you love remote control, you can always buy a power switch remote controlled.
