### ISSUE TITLE
fishes swim backwards

### ISSUE THREAD

**Issue by techsupport09** [thomwolf/GreatSand#38]
Everything is working well but, the fishes swim backwards in versions 1.5 and 1.54, (not in version 1 where they swam well, but this old version is not working anymore, it freeze in calibration process).
what could it be? is it normal?

**Comment by RasmusRPaulsen** [comment]
Hi,
Yes that is an issue with the more recent versions. It is due to the mount direction of the kinect in different setups. I am trying to do an automatic detection of this and update the animal behaviour accordingly. Is it possible for you to post the contents of your calibration.xml file?

**Comment by RasmusRPaulsen** [comment]
There is by the way also a toggle in the animal GUI called ""Draw flipped" - have you tried pressing that? An if you did, did it help on the backward swimming issue?

**Comment by thomwolf** [comment]
It works fine for me.

**Comment by techsupport09** [comment]
Sorry for the delay, it works.
