### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fallenarchon** [thomwolf/GreatSand#4]
Came here from your imgur album.  Thanks for open sourcing it!  Could you add a license to solidify your stance on commercial and home use?

**Comment by andrewbates09** [comment]
Cool addition to GitHub!

Did you get your inspiration from the [UCDavis Augmented Reality Sandbox](http://idav.ucdavis.edu/~okreylos/ResDev/SARndbox/)?

**Comment by thomwolf** [comment]
I fixed the licence ! Thanks !
And yes it is inspired by the UC Davis SARnbox !
