### ISSUE TITLE
will this work with windows 10?

### ISSUE THREAD

**Issue by nwsb** [thomwolf/GreatSand#42]
I downloaded this folder and tried to run the software. I get an error message that VCOMP120.DLL is missing. Searched the net found and installed a copy in the folder. now I get an error that the application was unable to start correctly (0xc000007b)

**Comment by RasmusRPaulsen** [comment]
It seems you have not installed the visual c++ Redistributable package. This installs the dll's needed for running applications compiled using visual studio:

https://www.microsoft.com/en-us/download/details.aspx?id=48145v

It is indeed running on windows 10.

Best,
Rasmus

**Comment by nwsb** [comment]
You’re absolutely correct some reason I thought I had already gotten those installed. However now I’m finding another issue every time I try to run calibration it gives me an error message that the calibration failed The reproduction area area too big?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomwolf** [comment]
Did you managed to fix the calibration issue @nwsb?
If not, feel free to re-open this issue!

**Comment by rosshaydenkelly** [comment]
I was having this same issue. I found that it was not the 2015 Redistributable Packages I needed, but instead the 2013 version. I have been stuck on this problem for the past hour until I installed the 2013 version from here - https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by RossKellyZA** [comment]
> It seems you have not installed the visual c++ Redistributable package. This installs the dll's needed for running applications compiled using visual studio:
> 
> https://www.microsoft.com/en-us/download/details.aspx?id=48145v
> 
> It is indeed running on windows 10.
> 
> Best,
> Rasmus

I was having this same issue. I found that it was **not** the 2015 Redistributable Packages I needed, but instead the 2013 version. I have been stuck on this problem for the past hour until I installed the 2013 version from here - https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by jortdevreeze** [comment]
> > It seems you have not installed the visual c++ Redistributable package. This installs the dll's needed for running applications compiled using visual studio:
> > https://www.microsoft.com/en-us/download/details.aspx?id=48145v
> > It is indeed running on windows 10.
> > Best,
> > Rasmus
> 
> I was having this same issue. I found that it was **not** the 2015 Redistributable Packages I needed, but instead the 2013 version. I have been stuck on this problem for the past hour until I installed the 2013 version from here - https://www.microsoft.com/en-us/download/details.aspx?id=40784

This solution worked for me as well. More specifically, installing the x64 version, and not the x86 version worked. You probably saved me an hours work :)
