### ISSUE TITLE
Color gradient didn't appear

### ISSUE THREAD

**Issue by hawkargeoscience** [thomwolf/GreatSand#43]
When I run the program, the contour line looks perfect but without colour gradient :( it appear white colour. Something wrong with the colour map, based on the terminal window information, there are some errors. Moreover, the Kinect Motor driver also does not appear on my driver list.

Just for your information, my Kinect is first generation product. I attached the list of the screen captures:
https://drive.google.com/drive/folders/14aywqUgpmQGxO-Fb41Ey34he9t5l43x7?usp=sharing
There are three files in these link:
1.Terminal window (Issue.txt)
2.Photo of the contour lines over the sand. (.jpg)
3.Screenshot of the Zedac drivers. (.jpg)

Best regards,
Hawkar Ali

**Comment by allensyl** [comment]
I have the same problem -- very nice contour lines but no colors.  I have adjusted the color map file and am able to get a single color to display, but it does not correspond to height nor does it recolor if the sand surface changes....it acts like ARSandbox if you don't include the -uhm 

HELP?

**Comment by cherwinski** [comment]
Have you tried to modify the boxlayout.txt file? The Kinect might think
your sand is out of bounds.  You could try dropping it 20 cm and see if
that helps.

**Comment by allensyl** [comment]
Where is boxlayout.txt in magic-sand?  I know where it is in SARndbox, but not magic-sand

**Comment by allensyl** [comment]
I gave up on the windows release and compiled it on Linux (Mint 18 Sylvia).  Only issue was ofxCv which needed to be one version earlier.  Otherwise it compiled with no problems and actually runs like it is supposed to!  Games work too!   Highly recommend it!

**Comment by cherwinski** [comment]
Does it reason to?

**Comment by thomwolf** [comment]
Nice to know that it works on linux @allensyl! And thanks for the feedback on ofxCv.
The Windows release issue was maybe due to an OpenGL compatibility issue of some sort but the file folder you shared was not what you think it was (it is about a field trip or something).
Feel free to re-open the issue if you want to dig deeper in that.
