### ISSUE TITLE
Setup mode

### ISSUE THREAD

**Issue by cherwinski** [thomwolf/GreatSand#45]
Is it possible to save calibration?  After the application is closed I have to re calibrate each time.

**Comment by thomwolf** [comment]
Well it should be saved by default...

**Comment by jsiwek2** [comment]
I also have the same issue.  The file is saved under "settings" but the program requires my students to calibrate over once they exit.    Has anyone found a solution for this issue?  Could it be just a Windows issue?

**Comment by jsiwek2** [comment]
Never mind, it was my own stupidity.  I kept forgetting to go up to the upper right hand corner and hit "RUNI" to load back in the calibration file.  Works perfect now.
