### ISSUE TITLE
Projector Model - LED short throw

### ISSUE THREAD

**Issue by ryanit** [thomwolf/GreatSand#46]
Hi, Thanks for sharing this amazing package.  Is the LED short throw projector suitable for this setting?

Thanks in advance.

**Comment by thomwolf** [comment]
Hi, I have tried with a cheap LED short projector (Unic UC50 DLP Projector) last year. It worked but it was no really usable in daylight condition. You have to turn off the light in the room to be able to see the colors on the sand and the effect is definitely not as strong as a conventional beamer.

**Comment by ryanit** [comment]
Thanks for the information.
