### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by KenCroft** [thomwolf/GreatSand#47]
Any idea on hardware requirements?  I built one out for my kids last year using a spare laptop and had no real issues.  I'd like to build one out for a charity organization but funding is a little tight.  

Any thoughts on what minimum requirements I should look for on processor/memory/GPU?

Thinking about a windows mini PC (haven't seen anything successful with RasPi, so can't go quite that cheap).

**Comment by thomwolf** [comment]
Hi @KenCroft, I think the most important is to have a graphic card with some OpenGL support (at least OpenGL 2.1 but support of OpenGL version >= 3.2 would be better).
That's the main issue with RasPi I think, its embedded graphic processor is really too basic.
Other than that the requirements are not very high.
