### ISSUE TITLE
kinect calibration - massive reprojector error

### ISSUE THREAD

**Issue by SimplesHampero** [thomwolf/GreatSand#48]
Hi - i'm running on macOSX High Sierra from the unpacked MacOS folder terminal instance on MacAir.

The viewer appears to run perfectly fine and first stage (low) calibration works well (lots of overlapping kinect reference chessboards though) but at the second stage it completes fine, then returns a projection error value which is in the hundreds.

I've run this with Kinect1 and Windows kinect with a cheapish projector and high-end benq as recommended by ARSandbox-original.

As i'm running it from down in the folder structure, debug isn't writing out to the data folder.

Aside from recompiling for high sierra (which I have no expertise in doing) I cannot think of anything more to try.

I'd planned to use this for an engagement event with children but zero hour is fast approaching so i'm hopeful of suggestions, please.

**Comment by RasmusRPaulsen** [comment]
Hi,
That sounds weird!
Are you sure you selected the "sand region" correctly. You should "drag a rectangle" to cover as much as possible of the sand surface, but exclude the sides of the box. Use either the Kinect RGB or Depth view as reference.
It is very strange that you see "overlapping reference boards"? 
Did you try to do it in a completely dark environment and use a white reference board on top of the box? The reference chessboard moves inward when OpenCV can not locate the pattern - and that might be the cause of your "overlapping chessboards".
Could you make a dump of the "console window output" ?
Best,
Rasmus

**Comment by SimplesHampero** [comment]
I think my graphics card just isn't up to the job. It is a mac air after all but I had hopes. 

I've followed the instructions correctly but will get the console dump to you when I can. 
I'm tied up on a work (employed) project for June so will try and get back on this in July when I'm back in front of the set up.

**Comment by ExpeditionSTEM** [comment]
I was getting the same error, and was using a wooden board with a matte side and a reflective side.  After switching to the reflective side, it worked.
