### ISSUE TITLE
Only can see white image screen, nothing can happen further

### ISSUE THREAD

**Issue by takleung** [thomwolf/GreatSand#49]
Hi, What should be next when I saw big white image screen. It says should be starting calibration but I did not find any key or menu on screen.

Thanks,
Ray

**Comment by thomwolf** [comment]
Hi @takleung, hard to say. Something in your computer setup or installation doesn't seems right.
Did you follow all the installation step on the release page (https://github.com/thomwolf/Magic-Sand/releases)?
Try to install everything again and if it doesn't work, please give us more information on your setup.

**Comment by takleung** [comment]
Hi, I fixed it finally. It seems USB driver not that stable.

By the way, may I know if any more themes I can get like volcano? Thank you
very much!

Thanks,
Ray

在 2018年7月18日週三 下午4:25，Thomas Wolf <notifications@github.com> 寫道：
