### ISSUE TITLE
DLL Issues, Windows 10

### ISSUE THREAD

**Issue by idrinkonweekends** [thomwolf/GreatSand#5]
Hello,

We spoke on Reddit about getting this running on windows 10. I was able to get my Kinect plugged in, and I believe I followed the steps fully, however I am running into much the same issues with getting the MagicSand.exe file to run. I currently get 3 DLL errors, stating they are missing.

MSVCP140.DLL
vcruntime140.DLL
CONCRT140.DLL

I searched my PC and I know the DLLs are installed in my system 32 folder 
(C:\Windows\System32), What folder path does the .exe use to look for these DLLs, or do you have any idea what may be happening?

Thanks!

**Comment by thomwolf** [comment]
Oh thanks for the follow up ! You probably should install the [Visual C++ run-time components](https://www.microsoft.com/en-us/download/details.aspx?id=48145) I have updated the readme about that (https://github.com/thomwolf/Magic-Sand/releases). Try installing both files supplied in the Visual C++ run-time components !

**Comment by idrinkonweekends** [comment]
Awesome! Tons of troubleshooting has moved us quite a bit forward.

As far as the DLL errors are concerned, it was fixed by installing both Visual C++ Files. (Before I had only been installing the X64)

After that I had issues getting my Kinect to register, I solved this by installing the Kinect SDK. Had to make sure it was for the Kinect V1 (SDK 1.0). ( I installed: https://www.microsoft.com/en-us/download/details.aspx?id=28782)

So, finally got the Kinect to register, installed the drivers as per the instructions, and the program seems to launch appropriately.

Used a monitor and a projector to have dual screens. Now the issue is it fails at calibration. I seems to work normally, it asks to flatten the sand, and the projector projects a white screen. once I press ok, it says stabilizing acquisition for a brief second before failing back to the Magic Sandbox.exe.

I can see the Kinect is working when I click on Display Kinect Depth View. I am unsure what is missing to get the calibration patterns to project. Thanks!

The log Scrren JPEG should be attached as well.

![log scrren](https://cloud.githubusercontent.com/assets/20735207/17271954/8ae849bc-563e-11e6-81bf-4bfc3cccb0aa.jpg)

**Comment by idrinkonweekends** [comment]
Hello! Ok, I got it working! Not sure what the actual issue was, but some adjusting of the Kinect and Projector distance relative to the box got it to eventually Calibrate! Thanks so much for your help, Im off to build the full sandbox and set up!

**Comment by thomwolf** [comment]
Great !! Happy to see that you managed to solve everything !
Do you mind answering a few questions so I can see if I should update the readme to share the knowledge you gathered in the process ?
That would be super nice !!
1. Which version of windows are you running ?
2. Which version of the kinect do you have ? Is it a 1414 ?
3. Regarding the kinect drivers. Did you follow the instruction of the release page and used the zadig software ? If I understand well, you say you first had to install the Microsoft Kinect SDK to be able to use the zadig software, is that right ?
4. Currently the first step of the calibration is to find a closed wall below the kinect (the wall of a sandbox) so the software knows where to put the calibration chessboard. I have never tested the soft without a close wall under underneath and I am not sure there is a good fallback in this case. Do you think that may have the case for your first unsuccessful tries ?

**Comment by idrinkonweekends** [comment]
Absolutely!!
1. Which version of windows are you running ?

-Windows 10 Home, 64bit
1. Which version of the kinect do you have ? Is it a 1414 ?

-yes, its a 1414 that I spliced.
1. Regarding the kinect drivers. Did you follow the instruction of the release page and used the zadig software ? If I understand well, you say you first had to install the Microsoft Kinect SDK to be able to use the zadig software, is that right ?

-Because I had never used the Kinect before when I plugged it in it only recognized the Motor (No Kinect Audio or Kinect Video). I had to install the SDK to get the system to recognize all three parts, then I was able to use Zadiq to switch drivers. Order was important I tried running Zadiq then SDK and it did not work.
1. Currently the first step of the calibration is to find a closed wall below the kinect (the wall of a sandbox) so the software knows where to put the calibration chessboard. I have never tested the soft without a close wall under underneath and I am not sure there is a good fallback in this case. Do you think that may have the case for your first unsuccessful 

-Yes, I believe that was the case. Must of my Calibration attempts where done on a flat wall, until I realized it was failing after searching for the  "walls of the box". So i used a box and messed with distance until it ran.

Let me know if there is anything else you think of and I will try to answer it!
