### ISSUE TITLE
libusb0.dll not found

### ISSUE THREAD

**Issue by ghost** [thomwolf/GreatSand#50]
Hi, I am running into an issue when I try to execute the **Magic-Sand.exe**, I have installed the Kinect SDK and I have installed the drivers but when I trying to install the executable I get this error, I have windows 10.
What should I do

**Comment by thomwolf** [comment]
Hi George, try to follow the installation instruction for Windows on the release page https://github.com/thomwolf/Magic-Sand/releases/tag/v1.5.4.1 and install all the required packages ( Visual C++ run-time components and Zadig).

**Comment by ghost** [comment]
Hi @thomwolf , Thank you I dont notice that I need to install libusb-win32( v1.2.6.0) driver from the driver menu.

### Below is the part I forget to follow.

Install the kinect drivers with the Free USB Driver tool Zadig:
Select your Xbox Camera, Xbox Audio and Xbox Motor in the drop down and then select the libusb-win32( v1.2.6.0) driver from the driver menu (click on the up/down arrows) and click install.
You need to do this operation two to three times: once for the camera, once for motor and once for the audio.
See the freenect github and ofxKinect github for more informations.
If there is a problem with the detection of the kinect, you can install the Kinect V1 (SDK 1.0) and run again Zadig.

**Comment by thomwolf** [comment]
Good thanks for the feedback @George35mk !
