### ISSUE TITLE
I have trouble to connect Kinect while running magic-sand

### ISSUE THREAD

**Issue by jamesho899** [thomwolf/GreatSand#52]
Hi,
I have trouble to connect Kinect while running magic-sand. (**Kinect works well via Kinect SDK 2.0**, but not work when I transfer driver to libusb-win32 by Zadig)
My environment are:
1. CPU Intel Corei5 w/  4G RAM
2. OS: Windows 10 64bit
2. Kinect V2 (XBox one)
3. Kinect SDK 1.8 or Kinect SDK 2.0 (I tried both)
I don't know what wrong I made, please kindly help. Thank you very very much.
Sincerely
James Ho

**Comment by saulomeirelles** [comment]
Hi,

I am having similar issue. Have you managed to solve it?

Cheers, Saulo

**Comment by RasmusRPaulsen** [comment]
Hi,
Magic-sand only works with Kinect V1 - sorry.
As discussed in other threads, it requires substantial and non-trivial work to make it work with Kinect V2 (due to for example non-linear lens distortions in the V2) 
And since Kinect V2 is now out of production - the motivation for doing so is not so high.
Kind regards,
Rasmus

**Comment by jamesho899** [comment]
Hi,
Thank you so much for your help and explanation, I'll try it on Kinect V1
these days. Thanks for your excellent project and explanation.
Sincerely
James Ho

**Comment by jamesho899** [comment]
Hi,
Thank you so much for your help and explanation, I'll try it on Kinect V1 these days. Thanks for your excellent project and explanation.
Sincerely
James Ho

**Comment by saulomeirelles** [comment]
Thanks, Rasmus.

Pardon my ignorance, but does it mean that the Kinect XBox isn't compatible?

Cheers, Saulo

**Comment by jsiwek2** [comment]
Hope this might help.  
https://www.youtube.com/watch?v=5AO8F4N1Wkw&t=411s
