### ISSUE TITLE
Run without Setup mode

### ISSUE THREAD

**Issue by krzychos7** [thomwolf/GreatSand#57]
There is way to start Magic-Sand in "Run mode"? Without Setup screen? When all calibration is done already. Also is the way to run with predefined number of rabbits and fishes?

**Comment by msriram** [comment]
Yes there is. The configuration is saved to a file and unless you move the setup, it will work just fine if you just click the Run button on the top right corner.

**Comment by msriram** [comment]
Please close this issue
