### ISSUE TITLE
Possible to add water simulation?

### ISSUE THREAD

**Issue by jamyam1982** [thomwolf/GreatSand#62]
Hello!

Thanks for the great project.

I was wondering if there was an easy way, or if someone has done it themselves already, to add the water simulation to this, perhaps by adding some code somewhere?

Thanks!

**Comment by RasmusRPaulsen** [comment]
It certainly can be done, but I would say that you have to be a rather competent C++ programmer to consider it easy.

I am not aware of existing versions of this software that has it but I have looked very much.
