### ISSUE TITLE
How to keep calibration 

### ISSUE THREAD

**Issue by afroway** [thomwolf/GreatSand#66]
Dear sir , 
Follow the step I have build a Magic-Sand box. It's really cool and funny.
But when close the app  I need to calibration again>.<  Have I miss something? 
Best Regards,

**Comment by jsiwek2** [comment]
It should stay calibrated by default.  Just make sure to hit "RUN" once you start the program.  Maybe this video will help:

https://www.youtube.com/watch?v=5AO8F4N1Wkw

**Comment by msriram** [comment]
Please close this issue. It is also a duplicate
