### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by JoeGetHub** [thomwolf/GreatSand#9]
I made it through a few errors, one being I had to use the x86 version of the Visual C++ software instead of the 64 bit version. I'm getting stuck on these two errors in a command window before the Magic Sand program crashes.

[ error ] ofAppGLFWWindow: 65542: WGL: The driver does not appear to support  OpenGL
[ error ] ofAppGLFWWindow: couldn't create GLFW window

I was going to use an older laptop for this project. Do I need something that supports OpenGL?

UPDATE:
I never installed the graphics card drivers on this laptop. I barely use it so the default Windows 7 x64 drivers were fine. The errors went away after installing the ATI Catalyst software.

**Comment by thomwolf** [comment]
Thanks for the update ! It is normal that you need to install the x86 runtime (the soft is 32bits), I will make it more explicit in the readme.
